class Video {
  final String id;
  final String title;
  final String thumbnailUrl;
  final String duration;
  final String cartoon;
  final DateTime timestamp;
  final List<int>? yasGrubu;

  const Video({
    required this.id,
    required this.title,
    required this.thumbnailUrl,
    required this.duration,
    required this.cartoon,
    required this.timestamp,
    this.yasGrubu,
  });
}

final List<Video> videos = [
  Video(
    id: 'pjSi1lSoWJM',
    title: 'Pepe 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/pjSi1lSoWJM/0.jpg',
    duration: '4:37',
    cartoon: 'pepe',
    timestamp: DateTime(2018, 9, 22),
    yasGrubu: [6, 9, 13],
  ),
  Video(
    id: '_02QBvqVdrs',
    title: 'Pepe 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/_02QBvqVdrs/0.jpg',
    duration: '7:18',
    cartoon: 'pepe',
    timestamp: DateTime(2018, 9, 29),
    yasGrubu: [6, 9, 13],
  ),
  Video(
    id: 'jDu1L8oAWRw',
    title: 'Pepe 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/jDu1L8oAWRw/0.jpg',
    duration: '10:53',
    cartoon: 'pepe',
    timestamp: DateTime(2018, 10, 11),
    yasGrubu: [6, 9, 13],
  ),
  Video(
    id: 'xTYSnGbPyho',
    title: 'Caillou 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/xTYSnGbPyho/0.jpg',
    duration: '24:25',
    cartoon: 'caillou',
    timestamp: DateTime(2016, 8, 25),
    yasGrubu: [6, 9, 13],
  ),
  Video(
    id: 'SXt71IqLHeU',
    title: 'Caillou 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/SXt71IqLHeU/0.jpg',
    duration: '29:08',
    cartoon: 'caillou',
    timestamp: DateTime(2016, 9, 20),
    yasGrubu: [6, 9, 13],
  ),
  Video(
    id: '2_K3WSi4Dw0',
    title: 'Caillou 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/2_K3WSi4Dw0/0.jpg',
    duration: '25:58',
    cartoon: 'caillou',
    timestamp: DateTime(2016, 10, 25),
    yasGrubu: [6, 9, 13],
  ),
  Video(
    id: 'xzlRsEy6lno',
    title: 'Niloya 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/xzlRsEy6lno/0.jpg',
    duration: '6:16',
    cartoon: 'niloya',
    timestamp: DateTime(2017, 2, 26),
    yasGrubu: [6],
  ),
  Video(
    id: 'Md0YTsoLG5I',
    title: 'Niloya 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/Md0YTsoLG5I/0.jpg',
    duration: '6:36',
    cartoon: 'niloya',
    timestamp: DateTime(2017, 3, 15),
    yasGrubu: [6],
  ),
  Video(
    id: 'l0zNyhx0p84',
    title: 'Niloya 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/l0zNyhx0p84/0.jpg',
    duration: '15:15',
    cartoon: 'niloya',
    timestamp: DateTime(2021, 8, 21),
    yasGrubu: [6],
  ),
  Video(
    id: 'OUOpQw69KD4',
    title: 'Maşa ile Koca Ayı 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/OUOpQw69KD4/0.jpg',
    duration: '6:38',
    cartoon: 'masa',
    timestamp: DateTime(2017, 12, 13),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'W-2F41CULFU',
    title: 'Maşa ile Koca Ayı 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/W-2F41CULFU/0.jpg',
    duration: '6:39',
    cartoon: 'masa',
    timestamp: DateTime(2017, 12, 23),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: '89FpEv7Jlm0',
    title: 'Maşa ile Koca Ayı 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/89FpEv7Jlm0/0.jpg',
    duration: '7:42',
    cartoon: 'masa',
    timestamp: DateTime(2017, 12, 29),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'E-mQyreQBFQ',
    title: 'Heidi 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/E-mQyreQBFQ/0.jpg',
    duration: '22:10',
    cartoon: 'heidi',
    timestamp: DateTime(2017, 11, 7),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'WzjjjYreUMI',
    title: 'Heidi 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/WzjjjYreUMI/0.jpg',
    duration: '22:34',
    cartoon: 'heidi',
    timestamp: DateTime(2017, 11, 11),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: '6nATzEfuCtE',
    title: 'Heidi 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/6nATzEfuCtE/0.jpg',
    duration: '23:31',
    cartoon: 'heidi',
    timestamp: DateTime(2017, 11, 16),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'smTVWwgnK2U',
    title: 'Pingu 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/smTVWwgnK2U/0.jpg',
    duration: '5:22',
    cartoon: 'pingu',
    timestamp: DateTime(2017, 12, 14),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'qwwiEqsSlCs',
    title: 'Pingu 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/qwwiEqsSlCs/0.jpg',
    duration: '5:23',
    cartoon: 'pingu',
    timestamp: DateTime(2017, 12, 15),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'qwwiEqsSlCs',
    title: 'Pingu 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/qwwiEqsSlCs/0.jpg',
    duration: '5:23',
    cartoon: 'pingu',
    timestamp: DateTime(2017, 12, 16),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'mCPPHzAPMo0',
    title: 'Şirinler 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/mCPPHzAPMo0/0.jpg',
    duration: '22:16',
    cartoon: 'sirinler',
    timestamp: DateTime(2019, 7, 23),
    yasGrubu: [9, 13],
  ),
  Video(
    id: '568Bkc2BX-U',
    title: 'Şirinler 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/568Bkc2BX-U/0.jpg',
    duration: '23:03',
    cartoon: 'sirinler',
    timestamp: DateTime(2019, 7, 24),
    yasGrubu: [9, 13],
  ),
  Video(
    id: '4FE-Jp3aOK4',
    title: 'Şirinler 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/4FE-Jp3aOK4/0.jpg',
    duration: '24:09',
    cartoon: 'sirinler',
    timestamp: DateTime(2019, 7, 25),
    yasGrubu: [9, 13],
  ),
  Video(
    id: 'tqI-3fPohpU',
    title: 'Tom ve Jerry 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/tqI-3fPohpU/0.jpg',
    duration: '5:25',
    cartoon: 'tomjerry',
    timestamp: DateTime(2021, 1, 14),
    yasGrubu: [9, 13],
  ),
  Video(
    id: 'O-oRAnsEWAk',
    title: 'Tom ve Jerry 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/O-oRAnsEWAk/0.jpg',
    duration: '5:18',
    cartoon: 'tomjerry',
    timestamp: DateTime(2021, 1, 15),
    yasGrubu: [9, 13],
  ),
  Video(
    id: '1-LGffBgUa4',
    title: 'Tom ve Jerry 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/1-LGffBgUa4/0.jpg',
    duration: '5:35',
    cartoon: 'tomjerry',
    timestamp: DateTime(2021, 1, 16),
    yasGrubu: [9, 13],
  ),
  Video(
    id: 'X4_2ED5bzfk',
    title: 'Pembe Panter 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/X4_2ED5bzfk/0.jpg',
    duration: '6:10',
    cartoon: 'pembe',
    timestamp: DateTime(2017, 3, 2),
    yasGrubu: [9, 13],
  ),
  Video(
    id: 'e9aVGbcNPyc',
    title: 'Pembe Panter 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/e9aVGbcNPyc/0.jpg',
    duration: '6:14',
    cartoon: 'pembe',
    timestamp: DateTime(2017, 3, 3),
    yasGrubu: [9, 13],
  ),
  Video(
    id: 'mgG3o-EJs9Y',
    title: 'Pembe Panter 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/mgG3o-EJs9Y/0.jpg',
    duration: '6:04',
    cartoon: 'pembe',
    timestamp: DateTime(2017, 3, 4),
    yasGrubu: [9, 13],
  ),
  Video(
    id: 'Dcr6fT-OZ3M',
    title: 'Gumball 1. ve 2. Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/Dcr6fT-OZ3M/0.jpg',
    duration: '21:18',
    cartoon: 'gumball',
    timestamp: DateTime(2016, 4, 8),
    yasGrubu: [13],
  ),
  Video(
    id: 'xU15WAksQHM',
    title: 'Gumball 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/xU15WAksQHM/0.jpg',
    duration: '11:19',
    cartoon: 'gumball',
    timestamp: DateTime(2021, 2, 2),
    yasGrubu: [13],
  ),
  Video(
    id: 'MJJEoT6bKe8',
    title: 'Adventure Time 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/MJJEoT6bKe8/0.jpg',
    duration: '10:15',
    cartoon: 'adventure',
    timestamp: DateTime(2020, 10, 2),
    yasGrubu: [13],
  ),
  Video(
    id: 'lZve77gomUY',
    title: 'Adventure Time 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/lZve77gomUY/0.jpg',
    duration: '20:38',
    cartoon: 'adventure',
    timestamp: DateTime(2020, 10, 3),
    yasGrubu: [13],
  ),
  Video(
    id: 'XpeM0JYVbi8',
    title: 'Adventure Time 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/XpeM0JYVbi8/0.jpg',
    duration: '10:26',
    cartoon: 'adventure',
    timestamp: DateTime(2020, 10, 4),
    yasGrubu: [13],
  ),
  Video(
    id: '7ZqJQZwmNuI',
    title: 'Adventure Time 1.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/7ZqJQZwmNuI/0.jpg',
    duration: '10:05',
    cartoon: 'surekli',
    timestamp: DateTime(2022, 2, 3),
    yasGrubu: [13],
  ),
  Video(
    id: '-UAyfFfZvLU',
    title: 'Adventure Time 2.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/-UAyfFfZvLU/0.jpg',
    duration: '10:36',
    cartoon: 'surekli',
    timestamp: DateTime(2022, 2, 4),
    yasGrubu: [13],
  ),
  Video(
    id: 'MYZ_rQxtgPU',
    title: 'Adventure Time 3.Bölüm',
    thumbnailUrl: 'https://i.ytimg.com/vi/MYZ_rQxtgPU/0.jpg',
    duration: '10:36',
    cartoon: 'surekli',
    timestamp: DateTime(2022, 2, 5),
    yasGrubu: [13],
  ),
  Video(
    id: '0Try_KIXdRs',
    title: 'Pepee / Bebee - Kalbim Kırıldı',
    thumbnailUrl: 'https://i.ytimg.com/vi/0Try_KIXdRs/0.jpg',
    duration: '1:07',
    cartoon: 'sarki',
    timestamp: DateTime(2014, 2, 14),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'adkeGXTtnUQ',
    title: 'Niloya - Tospik Şarkı',
    thumbnailUrl: 'https://i.ytimg.com/vi/adkeGXTtnUQ/0.jpg',
    duration: 'sarki',
    cartoon: 'niloyasarki',
    timestamp: DateTime(2014, 8, 13),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: '1cjKQIajOAg',
    title: 'Kral Şakir | Necati - Brokoli ',
    thumbnailUrl: 'https://i.ytimg.com/vi/1cjKQIajOAg/0.jpg',
    duration: '1:38',
    cartoon: 'sarki',
    timestamp: DateTime(2018, 12, 24),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'iYkQwpA86hU',
    title: 'Vücudunuzun İçine Doğru Bir Yolculuk',
    thumbnailUrl: 'https://i.ytimg.com/vi/iYkQwpA86hU/0.jpg',
    duration: '8:36',
    cartoon: 'egitici',
    timestamp: DateTime(2019, 10, 15),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'GbV8pU6XubE',
    title: 'Ağzınızın İçinde Bir Yolculuk',
    thumbnailUrl: 'https://i.ytimg.com/vi/GbV8pU6XubE/0.jpg',
    duration: '7:47',
    cartoon: 'egitici',
    timestamp: DateTime(2020, 7, 27),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: '0_WDvg7gwQo',
    title: 'İnsan Beynine Yolculuk',
    thumbnailUrl: 'https://i.ytimg.com/vi/0_WDvg7gwQo/0.jpg',
    duration: '7:42',
    cartoon: 'egitici',
    timestamp: DateTime(2020, 5, 4),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: 'XaEGrQZgrMw',
    title: 'İngilizce Meyveler ve Sebzeler',
    thumbnailUrl: 'https://i.ytimg.com/vi/XaEGrQZgrMw/0.jpg',
    duration: '7:42',
    cartoon: 'dil',
    timestamp: DateTime(2020, 5, 4),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: '6x0Lzvsk2LM',
    title: 'Almanca Sayılar',
    thumbnailUrl: 'https://i.ytimg.com/vi/6x0Lzvsk2LM/0.jpg',
    duration: '2:23',
    cartoon: 'dil',
    timestamp: DateTime(2016, 12, 8),
    yasGrubu: [3, 6, 9, 13],
  ),
  Video(
    id: '5xuZxGirWQI',
    title: 'Fransızca Alfabe Şarkısı',
    thumbnailUrl: 'https://i.ytimg.com/vi/5xuZxGirWQI/0.jpg',
    duration: '1:35',
    cartoon: 'dil',
    timestamp: DateTime(2016, 12, 8),
    yasGrubu: [3, 6, 9, 13],
  ),
];
